"""add improvement_credits to subscription

Revision ID: 2d3b2a4a8dd3
Revises: 1defa6cc1306
Create Date: 2026-07-16 23:50:19.113670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3b2a4a8dd3'
down_revision: Union[str, None] = '1defa6cc1306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='0' is required here: ADD COLUMN ... NOT NULL without a
    # default fails on both SQLite and PostgreSQL when the table already has
    # rows (existing free-plan users). The server_default only backfills
    # existing rows; new rows still get 0 via the Python-side model default.
    op.add_column(
        'subscription',
        sa.Column('improvement_credits', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'improvement_credits')
    # ### end Alembic commands ###
